---
# tasks file for customisation

# INSTALL AND CONFIGURE (OH-MY-)ZSH
- name: Clone Oh-My-Zsh repository
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1
    force: true

- name: Clone Powerlevel10k repository
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
    depth: 1
    force: true

- name: Install zsh-syntax-highlighting plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    force: true

#SET DEFAULT SHELL TO ZSH
# - name: Set loginshell
#   become: true
#   # shell: "chsh -s /usr/bin/zsh vagrant"
#   shell: "chsh -s /usr/bin/zsh {{ lookup('env', 'USER') }}"
#   tags: [zsh]

# Dash to Dock
- name: Configure Dash to Dock
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/{{ item.key }}"
    value: "{{ item.value[0] }}"
    state: present
  loop: "{{ lookup('dict', dashtodock) }}"

- name: Set Dock Favourites
  community.general.dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['org.gnome.Nautilus.desktop', 'librewolf.desktop']"
    state: present

# GNOME Terminal
- name: Configure GNOME terminal
  community.general.dconf:
    key: "/org/gnome/desktop/applications/terminal/{{ item.key }}"
    value: "{{ item.value[0] }}"
    state: present
  loop: "{{ lookup('dict', custom_gnome_terminal) }}"

# Custom Keybindings
# TODO: CREATE PATH IF IT DOES NOT EXIST
- name: Configure custom keybinding for terminal
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/{{ item.key }}"
    value: "{{ item.value[0] }}"
    state: present
  loop: "{{ lookup('dict', custom_keybinding_terminal) }}"

# TODO: remove existing print screen shortcut
- name: Configure custom keybinding for flameshot
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/{{ item.key }}"
    value: "{{ item.value[0] }}"
    state: present
  loop: "{{ lookup('dict', custom_keybinding_flameshot) }}"

- name: enable custom keybindings
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/']"

# Theme
- name: Download Yaru theme to specified folder
  become: true
  ansible.builtin.subversion:
    repo: "https://github.com/Jannomag/Yaru-Colors/trunk/Themes/Yaru-Red-dark/"
    dest: /usr/share/themes/Yaru-Red-dark

- name: Set GNOME theme
  community.general.dconf:
    key: "/org/gnome/desktop/interface/{{ item.key }}"
    value: "{{ item.value[0] }}"
    state: present
  loop: "{{ lookup('dict', gnome_interface_theme) }}"

# Wallpaper
- name: Copy wallpaper
  become: true
  ansible.builtin.copy:
    src: "files/wallpaper.jpg"
    dest: "/usr/share/backgrounds/custom-wallpaper.jpg"
    mode: '0744'
    force: true

- name: Set Background
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri-dark"
    value: "'file:///usr/share/backgrounds/custom-wallpaper.jpg'"
    state: present


# Extensions

# Requires user input - UAC
# ./gext install sound-output-device-chooser@kgshank.net
# ./gext install gestureImprovements@gestures
# ./gext install auto-move-windows@gnome-shell-extensions.gcampax.github.com